### ISSUE TITLE
tracking with DaSiamRPN

### ISSUE THREAD

**Issue by lenwenLin** [generalized-intelligence/GAAS#75]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version of GAAS
- [x] I checked the Gitbook documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I Googled/Binged the error messages generated by Ubuntu, Gazebo, and PX4
- [x] I have posted questions regarding Ubuntu, Gazebo, and PX4 in corresponding forums.

# Issue Template

## Context
Please provide any relevant information about your setup.
* Tutorial No.:[eg. Tutorial 4]
* Mavros: [eg. 0.18.4]
* ROS: [eg. Kinetic]
* Gazebo: [eg. 7]
* Ubuntu: [eg. 16.04]
* System Platform: [eg. X86]

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Logs

Copy console log and paste it here.

**Comment by lenwenLin** [comment]
having anyo
